# Make any updates -web also
test:
  s3_buckets:
    zipped_eps_images: XXXXXXXXXXXXXXXXXXXXXXX

development:
  s3_buckets:
    zipped_eps_images: eps.images.federalregister.gov
    private_images: private.images.fr2.local
    public_images: images.fr2.local
  ofr_flickr_group_id: 1058319@N21

staging:
  s3_buckets:
    zipped_eps_images: eps.images.federalregister.gov
    private_images: private.images.fr2.criticaljuncture.org
    public_images: images.fr2.criticaljuncture.org
  ofr_flickr_group_id: 1058319@N21

officialness_staging:
  s3_buckets:
    zipped_eps_images: eps.images.federalregister.gov
    private_images: private.images.fr-official.criticaljuncture.org
    public_images: images.fr-official.criticaljuncture.org

production:
  s3_buckets:
    zipped_eps_images: eps.images.federalregister.gov
    private_images: private.images.federalregister.gov
    public_images: images.federalregister.gov
  ofr_flickr_group_id: 1058319@N21
